### ISSUE TITLE
Can we have ticks go all the way up?

### ISSUE THREAD

**Issue by anaximander** [ryan-brown/dry-electrics-delegator#18]
Right now the tick marks on the x-axis are pretty small.  They're useful when reading along the axis, but the graph is pretty tall and it can be disorienting when looking at data at the top of the graph.  Can we have vertical lines/ticks that go all the way up the graph?  And maybe a border?  Not sure if lines along the y-axis would be useful but maybe that's something to consider too.

**Comment by ryan-brown** [comment]
Sounds like a job for Jon :)

**Comment by anaximander** [comment]
Thanks!
